{% set name = "notebook" %}
{% set version = "7.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 393ceb269cf9fdb02a3be607a57d7bd5c2c14604f1818a17dbeb38e04f98cbfa

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - jupyter-notebook = notebook.app:main
  no_link:
    - Menu/{{ name }}_menu.json

requirements:
  host:
    - python
    - pip
    - hatchling >=1.11
    - hatch-jupyter-builder >=0.5
    - jupyterlab >=4.5.3,<4.6
  run:
    - python
    - jupyter_server >=2.4.0,<3
    - jupyterlab >=4.5.3,<4.6
    - jupyterlab_server >=2.28.0,<3
    - notebook-shim <0.3,>=0.2
    - tornado >=6.2.0

app:
  entry: jupyter-notebook  # [not osx]
  entry: open ${PREFIX}/bin/jupyter_mac.command  # [osx]
  icon: jupyter.png
  summary: Jupyter Notebook
  type: web
  cli_opts:
    - name: port
      args: "--port %s"
      default: 8080
      summary: Server port ...

test:
  imports:
    - notebook
  requires:
    - pip
    - ripgrep
  commands:
    - pip check
    - jupyter notebook -h
    - jupyter-notebook -h
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | rg "@jupyter-notebook/lab-extension.*OK"  # [not win]
    - type labextensions | rg "@jupyter-notebook/lab-extension.*ok"  # [win]

about:
  home: https://github.com/jupyter/notebook
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - notebook/labextension/static/third-party-licenses.json
    - notebook/static/third-party-licenses.json
  summary: A web-based notebook environment for interactive computing
  description: |
    The Jupyter notebook is a web-based notebook environment for interactive computing.
  dev_url: https://github.com/jupyter/notebook
  doc_url: https://jupyter-notebook.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - gnestor
    - takluyver
    - lresende
    - bollwyvl
