{% set version = "5.7.10" %}

package:
  name: notebook
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/n/notebook/notebook-{{ version }}.tar.gz
    sha256: b10107e1438e7a564292aa32510e610c88844cae03c882fe5286b891792b5c11
    # add in missing react-dom js component, see:
    # https://github.com/jupyter/notebook/pull/4772
    patches:
      - 4772.patch
    # missing file needed, use the version that is included in the 6.0.1 release
  - url: https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js
    sha256: 0dcb93a5c7859e1fa909ffe239b591ec329bfea81bf5e059ecb1b6f7e1ca7058
    folder: notebook/static/components/react

build:
  number: 0
  entry_points:
    - jupyter-notebook = notebook.notebookapp:main
    - jupyter-nbextension = notebook.nbextensions:main
    - jupyter-serverextension = notebook.serverextensions:main
    - jupyter-bundlerextension = notebook.bundler.bundlerextensions:main

requirements:
  host:
    - python
    - pip
  run:
    - ipykernel
    - ipython_genutils
    - jinja2
    - jupyter_core >=4.4.0
    - jupyter_client >=5.2.0
    - nbconvert <6.0
    - nbformat
    - python
    - pyzmq >=17
    - send2trash
    - terminado >=0.8.1
    - tornado >=4.1,<7
    - traitlets >=4.2.1
    - prometheus_client
    - ipaddress  # [py2k]

app:
  entry: jupyter-notebook  # [not osx]
  entry: open ${PREFIX}/bin/jupyter_mac.command  # [osx]
  icon: jupyter.png
  summary: Jupyter Notebook
  type: web
  cli_opts:
    - name: port
      args: --port %s
      default: 8080
      summary: Server port ...

test:
  commands:
    - jupyter notebook -h
    - jupyter nbextension -h
    - jupyter serverextension -h
    - jupyter bundlerextension -h
  imports:
    - notebook

about:
  home: http://jupyter.org
  license: BSD 3-clause
  license_family: BSD
  license_file: COPYING.md
  summary: A web-based notebook environment for interactive computing
  description: |
    Jupyter Notebook is a web application, a browser-based tool for interactive
    authoring of documents which combine explanatory text, mathematics, computations
    and their rich media output.
  doc_url: https://jupyter-notebook.readthedocs.org/en/latest/
  doc_source_url: https://github.com/jupyter/notebook/blob/master/docs/source/index.rst
  dev_url: https://github.com/jupyter/notebook

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - gnestor
    - takluyver
