travis:
  secure:
    BINSTAR_TOKEN: qsZeI+sNKhouUR3a1VOUOy8JoNpZAmzkxIFwbzAv1SyafE2JpRongHr5O4tZCxzv1OVGEwgyMYwWtDf0bGofhBIWC/iDiZRGGi8sbf1XdcXy3xp4em0cBbOmQYsTqeesisRimqGY6QaswHEh4mO2wG+faYNdBf4V/Y+jfvMqqgoYYQ8BLD6mbGN93NkmPDoqUVGIoGUnRorzigg755bnF8jvqJuzq1hOhPkfsD7OQkg6psezUd+QVUPnR77GGSqaudZdah8E5Sw/v8jYvvcXd26KfGdG2U5rsE2t8i8oqqqvRhBGX4T2xI2du40zUN0sj42RAASgf9whn33KNCLujxtmG0/v0YG30IIDrD/oRzCO1dMxwVoX1PyUtUP7IDKyY0ErS9GsN7xSOZHRudlLydg6WSQwh/cOXVEyniRRkmMygEFruz5/ee2Dx3TxDh2dQaiUY6Vcl+Fdoq1GCnhR69Vcc6B/8h6NW1csQ2tno3SdML3TkwddWIvj4xuJMs90bHeIga8n8MKOwU55aq3QKyS+2zj/trBQ7R9/y6ZCNjbREE8vFohJHa4DzY6PuQqudaJLkIxJR3PRA8Pk5qHVjLiej43f7RSr84Awdnupoy23Ft88YDdkinXhPvZxQ4fXg5eDi0pn30sXCyzM2u1eoavnqFotmtKDLtxukm5pCXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
